version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/ChatBot
      dockerfile: ChatBot.Api/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__ChatBotDb=Server=db,1433;Database=ChatBotDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1434:1433"